### ISSUE TITLE
when i run "catkin build" come out zhis error. how can i fix it? thanks..

### ISSUE THREAD

**Issue by ZY-Peng** [InnopolisAero/nbv_exploration_planner#6]
Traceback (most recent call last):
File "/usr/bin/catkin", line 11, in <module>
load_entry_point('catkin-tools==0.6.1', 'console_scripts', 'catkin')()
File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 272, in main
catkin_main(sysargs)
File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
sys.exit(args.main(args) or 0)
File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 422, in main
summarize_build=opts.summarize  # Can be True, False, or None
File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 283, in build_isolated_workspace
workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 96, in find_packages
raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "voxblox":

- nbv_exploration_planner/voxblox/voxblox
- voxblox/voxblox
Multiple packages found with the same name "voxblox_msgs":
- nbv_exploration_planner/voxblox/voxblox_msgs
- voxblox/voxblox_msgs
Multiple packages found with the same name "voxblox_ros":
- nbv_exploration_planner/voxblox/voxblox_ros
- voxblox/voxblox_ros
Multiple packages found with the same name "voxblox_rviz_plugin":
- nbv_exploration_planner/voxblox/voxblox_rviz_plugin
- voxblox/voxblox_rviz_plugin
- 
when i run "catkin build" come out zhis error. how can i fix it? thanks..

**Comment by wzya112** [comment]
使用sudo catkin build。之后可能还会出现错误：
1. voxblox_manager.cpp:68:78: error: no matching function for call to ‘voxblox::TsdfServer::TsdfServer(const ros::NodeHandle&, const ros::NodeHandle&, const string&)’
68 | : VoxbloxManager(nh, nh_private, params), tsdf_server_(nh, nh_private, ns) {
| ^
2. voxblox_manager.cpp:100:78: error: no matching function for call to ‘voxblox::EsdfServer::EsdfServer(const ros::NodeHandle&, const ros::NodeHandle&, const char [1])’
100 | : VoxbloxManager(nh, nh_private, params), esdf_server_(nh, nh_private, "") {
| ^
需要在voxblox_manager,cpp中将第100行和第68行的esdf_server_与tsdf_server_的最后一个参数去掉。
